format_version: 2
common:
  parent: &parent
    Apipeline:
      pipeline: A
      stage: apply
  plan: &plan
    clean_workspace: true
    secure_variables: 
      user: "90mE/w2Ux+xlqFipNLdINA=="
      password: "8sXkDq7gmd56t2NnkJExsg=="
    jobs:
      plan:
        tasks:
        - script: |
            curl --insecure -u ${user}:${password} ${GO_SERVER_URL}/run/{$GO_PIPELINE_NAME}/${GO_PIPELINE_COUNTER}/apply
            echo "#{theName} PLAN!"
  apply: &apply
    approval:
      type: manual # Require someone in the UI to manually approve the execution of this stage
      users:
        - superman
    clean_workspace: true
    jobs:
      apply:
        tasks:
        - script: |
            echo "APPLY!"
  materials: &materials
    thing:
      branch: master
      git: https://github.com/plainsane/gogogadgetcd-material.git
      destination: repo
  basePipeline: &basePipeline
    materials:
      <<: *materials
      <<: *parent
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply

pipelines:
  A:
    group: GOgogadgetCD
    parameters:
      theName: A
    materials:
      <<: *materials
    stages:
      - plan:
          <<: *plan
      - apply:
          <<: *apply
  B:
    group: GOgogadgetCD
    parameters:
      theName: B
    <<: *basePipeline
  C:
    group: GOgogadgetCD
    parameters:
      theName: C
    <<: *basePipeline
